
line-length = 160
target-version = "py37"

exclude = [
    "*.pyi",
    ]
# extend-select = [
#   "UP030",
#   "UP031",
#   "UP032",
# ]



[lint]
select = ["ALL"]

extend-ignore = [
    "FBT001", # boolean positional argument
    "PD008", # .at with pandas is fine with me
    "PD011", # Use .values instead of .to_numpy() - I prefer not to copy arrays
    "RUF059", # Allow unused variables
    "FIX002", # TODO are OK
    "FIX004", # HACK is OK

    "SIM109", # multiple equality comparisons are more performant than a set in small cases
    "PLR1714", # multiple equality comparisons are more performant than a set in small cases


    "D415", # First docstring line should end with a period, question mark, or exclamation point
    "DTZ004", # utcfromtimestamp makes sense for atmosphere model
    "PGH003", # type ignoring makes sense for numba-related things
    "S102", # Yes, exec is dangerous but it can be quite useful as well

    "PYI056", # changing __all__

    "RUF012", # not using typing today
    "PERF403", # obvious, use an autofix if one becomes available
    "PERF203", # `try`-`except` within a loop incurs performance overhead
    "PERF401", # PERF401 Use a list comprehension to create a transformed list

    "PLR1730", # use of min/max are less performant than `if
    "PLC0415", # Allow lazy imports

    # chemicals specific
    "E701", # lots of this here

    "S302", # marshal is OK
    "SIM116", # 3 if statements does not require a dict

    # maybe these
    "PLE0605",
    "PLE0604",

    "TD002","TD003","TD004","TD005",


    # Originally from astropy's pyproject.toml, see about removing many of them later

    "A00",
    "ANN",
    "ARG001", "ARG002", "ARG005",
    "B004",
    "B006",
    "B007",
    "B008",
    "B904",
    "BLE001",
    "C408", "C416",
    "C901",
    "COM812",
    "COM819",
    "D101",
    "D102",
    "D103",
    "D105",
    "D107",
    "D200",
    "D203",
    "D205",
    "D212", "D213",
    "D403",
    "D404",
    "D400",
    "D401",
    "D413",
    "D414",
    "D417",
    "DTZ001", "DTZ007",
    "E501",
    # "E711",
    "E721",
    "E731",
    "E741",
    "EM",
    "ERA001",
    "F841",
    "E722",
    "FBT002", "FBT003",
    "N8",
    "PLR2004",
    "PLR0911",
    "PLR0912",
    "PLR5501",
    "PLR0913",
    "PLR0915",
    "PLW2901",
    "PLW0603",
    "PTH",
    "RET",
    "RSE102",
    "RUF001",
    "RUF003",  # greek characters are used in this project e.g. for allotropes
    "RUF005",  # this one is not micropython compatible
    "S101",
    "S110",
    "S112",
    "S311",
    "S310",
    "SIM102",
    "SIM105",
    "SIM108",
    "SIM114",
    "SIM115",
    "SIM118",
    "SIM300",
    "SLF001",
    "T201",
    "TRY003",
    "TRY201",
    "TRY300",
    "TRY301",

    "PYI024", # PYI024 Use `typing.NamedTuple` instead of `collections.namedtuple
]
[lint.mccabe]
max-complexity = 10
