language: c
os:
  - osx
  - linux
compiler:
  - "2.7"
  - "3.4"
  - "3.5"
#  - "3.6"
env:
  - SCIPY_VER="scipy>=0.18.0" 
matrix:
  fast_finish: true
notifications:
  email: false
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CONDA_OS='Linux'; else CONDA_OS='MacOSX'; fi;
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-${CONDA_OS}-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$CC numpy scipy pandas matplotlib pip pytest sympy
  - source activate test-environment
  - conda install $SCIPY_VER
  - pip install numpydoc fluids coolprop pytest-cov coveralls
  - python setup.py -q install
script:
  - cd tests
  - py.test . -v --cov-report html --cov=thermo --cov-report term-missing -m "not meta_Chemical and not slow and not rdkit";
after_success:
  - coveralls
