# File after https://github.com/jowr/jopy/blob/master/appveyor.yml, copyright predominately Jorrit Wronski
# Tell appveyor to not use msbuild
build: false

environment:
  matrix:
    - PYTHON: 2.7
    - PYTHON: 3.5
#    - PYTHON: 3.4

platform:
  - x86
  - x64

init:
  - "ECHO %PYTHON%"
#  - ps: if($env:PYTHON -eq "2.7" -and $env:Platform -eq "x64"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda2-latest-Windows-x86_64.exe' C:\Miniconda.exe; echo "Done"}
#  - ps: if($env:PYTHON -eq "2.7" -and $env:Platform -eq "x86"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda2-latest-Windows-x86.exe' C:\Miniconda.exe; echo "Done"}
#  - ps: if($env:PYTHON -eq "3.4" -and $env:Platform -eq "x64"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe' C:\Miniconda.exe; echo "Done"}
#  - ps: if($env:PYTHON -eq "3.4" -and $env:Platform -eq "x86"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86.exe' C:\Miniconda.exe; echo "Done"}
#  - ps: if($env:PYTHON -eq "3.5" -and $env:Platform -eq "x64"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe' C:\Miniconda.exe; echo "Done"}
#  - ps: if($env:PYTHON -eq "3.5" -and $env:Platform -eq "x86"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86.exe' C:\Miniconda.exe; echo "Done"}
#  - cmd: C:\Miniconda.exe /S /D=C:\Miniconda
  - cmd: SET PATH=C:\Miniconda36\Scripts;C:\Miniconda\Scripts;%PATH%
  - cmd: conda update -yq conda
  - cmd: conda install -yq conda-env conda-build 
  - cmd: conda create -yq -n condaenv python=%PYTHON%

install:
  - cmd: activate condaenv
  - cmd: conda install -yq numpy scipy pip pytest pandas matplotlib
  - cmd: pip install pytest-cov coveralls sympy fluids coolprop
  - cmd: python setup.py install

test_script:
  - cmd: py.test --cov-report html --cov=thermo -m "not slow and not sympy and not rdkit"
